import json
import flask
import requests
import os

import urllib.request
import urllib.parse
import urllib.error

from flask import redirect, request, render_template, url_for, Blueprint, send_from_directory, current_app, session
from flask_login import login_required
from app.app import db

from app.models import Generation


from app.blueprints.generation.helper import blueprint_add, generation_add

ip_adapter_headshot = Blueprint("ip_adapter_headshot", __name__, template_folder='templates', static_folder='static')

# Need to import Blueprint after creating blueprint since that's the name of my model. Bad name need to fix later.
from app.models import Blueprint

@ip_adapter_headshot.route('/')
@login_required
def index():
    if(not Blueprint.query.filter_by(id=3).first() or Blueprint.query.filter_by(id=3).first().title != 'ip_adapter_headshot'):
        blueprint_add('ip_adapter_headshot', 3)
    base_url = '/generation/ip_adapter_headshot'
    return render_template('ip_adapter_headshot/index.html', base_url=base_url)

# This is to view the image generated by ComfyUI. 
@ip_adapter_headshot.route("/<endpoint>", methods=['GET'])
@login_required
def get_endpoint(endpoint=None):
    args = flask.request.args
    if len(args) > 0:
        queries = urllib.parse.urlencode(dict(args))
        try:
            res = urllib.request.urlopen(
                f"http://127.0.0.1:8188/{endpoint}?{queries}")
            print(res.url)
            generation_add(res.url, Blueprint.query.filter_by(title="ip_adapter_headshot").first().id)
            return res
        except urllib.error.HTTPError as e:
            return e.read()

    req = urllib.request.Request(
        f"http://127.0.0.1:8188/{endpoint}")
    try:
        response = urllib.request.urlopen(req)
        return response
    except urllib.error.HTTPError as e:
        return e.read()

# todo: 'add get and post to javascript or figure out how to make specfic routes '
# This is to generate the image by ComfyUI. Is this the only thing that generates and returns the image?
@ip_adapter_headshot.route("/<endpoint>", methods=['POST'])
@login_required
def post_endpoint(endpoint=None):
    payload = flask.request.get_json()
    data = json.dumps(payload).encode('utf-8')
    req = urllib.request.Request(
        f"http://127.0.0.1:8188/{endpoint}", data=data)
    try:
        response = urllib.request.urlopen(req)
        return response
    except urllib.error.HTTPError as e:
        return e.read()
    

    

@ip_adapter_headshot.route("/save", methods=['POST'])
@login_required
def save():
    try:
        title = request.form['save-title']
        desc = request.form['save-desc']
        print(title, desc)
        print("save")
        return redirect(url_for("ip_adapter_headshot.index"))
    except KeyError as e:
        print(f"Error: {e} is missing in the form data.")
        # You can handle the error here, e.g., by returning an error response or redirecting to an error page
        return redirect(url_for("ip_adapter_headshot.index"))  
